import vue from '@welldot/lint/vue';
import eslintConfigPrettier from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';
import vueParser from 'vue-eslint-parser';

export default [
  ...vue,
  // `flat/recommended` ships template formatting rules (`vue/html-indent`,
  // …) that fight Prettier; turn them off and let `prettier/prettier` win.
  eslintConfigPrettier,
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        // `vue-eslint-parser` handles the SFC and delegates `<script lang="ts">`
        // to the TS parser; without it any TS syntax is a parse error.
        parser: tseslint.parser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
    },
  },
  {
    rules: {
      // `~icons/*` are virtual modules generated by `unplugin-icons`.
      'import-x/no-unresolved': ['error', { ignore: ['^~icons/'] }],
      'import-x/extensions': [
        'error',
        'ignorePackages',
        {
          // `pathGroupOverrides` is only read alongside a `pattern` object.
          pattern: { js: 'never', ts: 'never', tsx: 'never' },
          pathGroupOverrides: [{ pattern: '~icons/**', action: 'ignore' }],
        },
      ],
    },
  },
  {
    // Tests define throwaway components inline with `render` functions.
    files: ['**/*.test.ts'],
    rules: {
      'vue/one-component-per-file': 'off',
      'vue/component-api-style': 'off',
    },
  },
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      '.turbo/**',
      'vite.config.ts',
      'vitest.config.ts',
      'eslint.config.js',
    ],
  },
];
