// Types
export type {
  AirliftEvent,
  AquiferAnalysis,
  Attachment,
  BoreHole,
  Cave,
  CementPad,
  Centralizer,
  ConstantRateEvent,
  Constructive,
  Fracture,
  Geologic,
  HistoryLogEntry,
  HoleFill,
  HydrodynamicEvent,
  HydrodynamicEventBase,
  LevelReading,
  Lithology,
  Location,
  LocationProperties,
  MonthlyGrant,
  Permit,
  PermitCondition,
  PumpElectrical,
  PumpInstallation,
  PumpingStep,
  RecoveryOnlyEvent,
  RecoveryPhase,
  Reduction,
  SectionKey,
  SectionVisibility,
  SpotMeasurementEvent,
  StepDrawdownEvent,
  SurfaceCase,
  Texture,
  VolumeLimit,
  Well,
  WellCase,
  WellId,
  WellScreen,
} from './types/well.types';

export type {
  DiameterUnits,
  FlowUnits,
  LengthUnits,
  PowerUnits,
  Units,
  UnitsTypes,
} from './types/units.types';

// Validators
export {
  AirliftEventSchema,
  AquiferAnalysisSchema,
  AttachmentSchema,
  BoreHoleSchema,
  CaveSchema,
  CementPadSchema,
  CentralizerSchema,
  ConstantRateEventSchema,
  FractureSchema,
  HistoryLogEntrySchema,
  HoleFillSchema,
  HydrodynamicEventBaseSchema,
  HydrodynamicEventSchema,
  LevelReadingSchema,
  LithologySchema,
  LocationPropertiesSchema,
  LocationSchema,
  MonthlyGrantSchema,
  PermitConditionSchema,
  PermitSchema,
  PumpElectricalSchema,
  PumpInstallationSchema,
  PumpingStepSchema,
  RecoveryOnlyEventSchema,
  RecoveryPhaseSchema,
  ReductionSchema,
  SpotMeasurementEventSchema,
  StepDrawdownEventSchema,
  SurfaceCaseSchema,
  TextureSchema,
  VolumeLimitSchema,
  WellCaseSchema,
  WellIdSchema,
  WellSchema,
  WellScreenSchema,
  parseWell,
} from './validators/well.validators';

// Format utilities (serialise/deserialise .well format only)
export {
  SECTION_KEYS,
  checkIfProfileIsEmpty,
  convertProfileFromJSON,
  deserializeWell,
  isWellEmpty,
  profileToWell,
  redactWell,
  serializeWell,
} from './utils/well.utils';

export type { TextureCode, TextureOption } from './types/textures';
export { FGDC_TEXTURES_OPTIONS } from './utils/fgdc.textures';

// Backward-compat alias for app migration
export type { Well as Profile } from './types/well.types';

// Units conversion utilities
export {
  cubicMeterPerHourToLitersPerSecond,
  cubicMeterPerHourToUsGallonsPerMinute,
  cubicMetersToLiters,
  cvToKilowatts,
  decimalDegreesToDms,
  dmsToDecimalDegrees,
  feetToMeters,
  flowFromCanonical,
  flowToCanonical,
  hoursToMinutes,
  hpToKilowatts,
  inchesToMm,
  kilopascalToPsi,
  kilowattsToCv,
  kilowattsToHp,
  litersPerSecondToCubicMeterPerHour,
  litersToCubicMeters,
  metersToFeet,
  minutesToHours,
  mmToInches,
  mmToSlotNumber,
  powerFromCanonical,
  powerToCanonical,
  psiToKilopascal,
  slotNumberToMm,
  squareMeterPerDayToSquareMeterPerSecond,
  squareMeterPerSecondToSquareMeterPerDay,
  usGallonsPerMinuteToCubicMeterPerHour,
} from './utils/units';
export type { DmsCoordinate } from './utils/units';
