// Types
export type {
  AirliftEvent,
  AquiferAnalysis,
  Attachment,
  BoreHole,
  Cave,
  CementPad,
  Centralizer,
  ConstantRateEvent,
  Constructive,
  DeclaredVolume,
  Filtration,
  Fracture,
  Geologic,
  HistoryLogEntry,
  HoleFill,
  HydrodynamicEvent,
  HydrodynamicEventBase,
  Laboratory,
  LevelReading,
  Lithology,
  Location,
  LocationProperties,
  Meter,
  MeterReading,
  MonthlyGrant,
  OperatingRegime,
  Parameter,
  Permit,
  PermitCondition,
  ProductionEntry,
  ProductionEntryBase,
  PumpElectrical,
  PumpInstallation,
  PumpingStep,
  Purge,
  PurgeReading,
  RecoveryOnlyEvent,
  RecoveryPhase,
  Reduction,
  ResultQualifier,
  ResultValidation,
  SamplingPoint,
  SectionKey,
  SectionVisibility,
  SpotMeasurementEvent,
  StepDrawdownEvent,
  SurfaceCase,
  Texture,
  TimeResolution,
  VolumeLimit,
  WaterQualityResult,
  WaterSample,
  Well,
  WellCase,
  WellId,
  WellScreen,
  WellStatus,
} from './types/well.types';

export type {
  DiameterUnits,
  FlowUnits,
  LengthUnits,
  PowerUnits,
  Units,
  UnitsTypes,
  VolumeUnits,
} from './types/units.types';

// Validators
export {
  AirliftEventSchema,
  AquiferAnalysisSchema,
  AttachmentSchema,
  BoreHoleSchema,
  CaveSchema,
  CementPadSchema,
  CentralizerSchema,
  ConstantRateEventSchema,
  DeclaredVolumeSchema,
  FiltrationSchema,
  FractureSchema,
  HistoryLogEntrySchema,
  HoleFillSchema,
  HydrodynamicEventBaseSchema,
  HydrodynamicEventSchema,
  LaboratorySchema,
  LevelReadingSchema,
  LithologySchema,
  LocationPropertiesSchema,
  LocationSchema,
  MeterReadingSchema,
  MeterSchema,
  MonthlyGrantSchema,
  OperatingRegimeSchema,
  ParameterSchema,
  PermitConditionSchema,
  PermitSchema,
  ProductionEntryBaseSchema,
  ProductionEntrySchema,
  PumpElectricalSchema,
  PumpInstallationSchema,
  PumpingStepSchema,
  PurgeReadingSchema,
  PurgeSchema,
  RecoveryOnlyEventSchema,
  RecoveryPhaseSchema,
  ReductionSchema,
  ResultQualifierSchema,
  ResultValidationSchema,
  SamplingPointSchema,
  SpotMeasurementEventSchema,
  StepDrawdownEventSchema,
  SurfaceCaseSchema,
  TextureSchema,
  TimeResolutionSchema,
  VolumeLimitSchema,
  WaterQualityResultSchema,
  WaterSampleSchema,
  WellCaseSchema,
  WellIdSchema,
  WellSchema,
  WellScreenSchema,
  WellStatusSchema,
  parseWell,
} from './validators/well.validators';

// Format utilities (serialise/deserialise .well format only)
export {
  SECTION_KEYS,
  checkIfProfileIsEmpty,
  convertProfileFromJSON,
  deserializeWell,
  isWellEmpty,
  profileToWell,
  redactWell,
  serializeWell,
} from './utils/well.utils';

export type { TextureCode, TextureOption } from './types/textures';
export { FGDC_TEXTURES_OPTIONS } from './utils/fgdc.textures';

// Water quality vocabulary and limit sets (since v2.3)
export {
  BR_GM_MS_888_2021,
  EU_2020_2184,
  NEPHELOMETRIC_TURBIDITY_CODES,
  WATER_QUALITY_LIMIT_SETS,
  WHO_GDWQ_2022,
  getLimitSet,
} from './vocab/waterQuality.limits';
export type { Limit, LimitBasis, LimitSet } from './vocab/waterQuality.limits';
export {
  WATER_QUALITY_PARAMETERS,
  WATER_QUALITY_UNITS,
  WATER_QUALITY_VOCABULARY_VERSION,
  getParameterDefinition,
  isKnownParameter,
  parameterKey,
} from './vocab/waterQuality.vocab';
export type {
  ParameterDefinition,
  ParameterForm,
  ParameterGroup,
  ParameterUnit,
} from './vocab/waterQuality.vocab';

// Backward-compat alias for app migration
export type { Well as Profile } from './types/well.types';

// Units conversion utilities
export {
  concentrationFromCanonical,
  concentrationToCanonical,
  cubicFeetToCubicMeters,
  cubicMeterPerHourToLitersPerSecond,
  cubicMeterPerHourToUsGallonsPerMinute,
  cubicMetersToCubicFeet,
  cubicMetersToLiters,
  cubicMetersToUsGallons,
  cvToKilowatts,
  decimalDegreesToDms,
  dmsToDecimalDegrees,
  expandedToStandardUncertainty,
  feetToMeters,
  flowFromCanonical,
  flowToCanonical,
  hoursToMinutes,
  hpToKilowatts,
  inchesToMm,
  kilopascalToPsi,
  kilowattsToCv,
  kilowattsToHp,
  litersPerSecondToCubicMeterPerHour,
  litersToCubicMeters,
  metersToFeet,
  milliSiemensPerCmToMicroSiemensPerCm,
  milliSiemensPerMeterToMicroSiemensPerCm,
  minutesToHours,
  mmToInches,
  mmToSlotNumber,
  normalizeColorUnit,
  powerFromCanonical,
  powerToCanonical,
  psiToKilopascal,
  slotNumberToMm,
  squareMeterPerDayToSquareMeterPerSecond,
  squareMeterPerSecondToSquareMeterPerDay,
  turbidityCodeForUnit,
  usGallonsPerMinuteToCubicMeterPerHour,
  usGallonsToCubicMeters,
  volumeFromCanonical,
  volumeToCanonical,
} from './utils/units';
export type { ConcentrationUnits, DmsCoordinate } from './utils/units';
