import { easeCubic } from 'd3';
import {
  ComponentsClassNames,
  CssVarsConfig,
  RenderConfig,
} from '~/types/render.types';

export const INTERACTIVE_RENDER_CONFIG: RenderConfig = {
  zoom: true,
  pan: true,
  zoomLevel: 1,
  animation: { duration: 600, ease: easeCubic },
  geologic: { xLeft: 6, xRightInset: 56 },
  layout: { pocoWidthRatio: 0.25, pocoCenterRatio: 0.11 },
  caves: {
    pathSteps: 40,
    amplitude: { ratio: 0.12, min: 1, max: 5.5 },
  },
  fractures: {
    widthMultiplier: 1.2,
    hitBuffer: { single: 8, swarm: 15 },
    swarm: {
      lineCountBase: 3,
      lineCountVariance: 11,
      spread: 18,
      centralStrokeWidth: 1.2,
      sideStrokeWidthBase: 0.6,
      sideStrokeWidthVariance: 0.6,
    },
    single: { mainStrokeWidth: 1.8, crackStrokeWidth: 0.7 },
  },
  construction: {
    cementPad: { widthMultiplier: 0.9, thicknessMultiplier: 1.3 },
    surfaceCase: { diameterPaddingRatio: 0.1 },
  },
  labels: {
    active: false,
    typeLabels: { fracture: 'fratura', cave: 'caverna' },
    style: {
      fontSize: 10.5,
      depthTipHeight: 11,
      depthTipPadX: 2,
      descriptionXOffset: 78,
      descriptionMaxWidth: 226,
      stackingLineHeight: 11,
      stackingGap: 0,
    },
  },
  unitLabels: {
    active: false,
    xOffset: 0,
    stripWidth: 8,
    fontSize: 5.5,
    minHeightForText: 8,
    innerDividerWidth: 1.5,
    outerEdgeWidth: 0.6,
  },
  constructionLabels: {
    active: false,
    fontSize: 7.5,
    xOffset: 10,
    labelRadius: 2,
    labels: {
      wellCasePrefix: 'Revest.',
      wellScreenPrefix: 'Filtro',
      wellScreenSlotPrefix: 'Ranhura:',
    },
  },
  textures: {
    pad: { background: '#ffffff', stroke: '#303030' },
    conflict: { stroke: '#E52117' },
    cave_dry: { size: 8, stroke: '#333333', background: '#ffffff' },
    cave_wet: { size: 8, stroke: '#1a6fa8', background: '#ffffff' },
    seal: { background: '#ffffff' },
    gravel_pack: { background: '#ffffff' },
    well_screen: { size: 40, strokeWidth: 2, background: '#ffffff' },
    surface_case: {
      orientation: ['vertical', 'horizontal'],
      size: 4,
      strokeWidth: 1,
      shapeRendering: 'crispEdges',
      stroke: '#303030',
      background: '#fff',
    },
  },
  legend: {
    title: 'LEGENDA',
    fontSize: 7,
    itemWidth: 110,
    height: 44,
    padding: 4,
    maxWidth: 700,
    borderRadius: 3,
    labels: {
      fractureSingle: 'Fratura simples',
      fractureSwarm: 'Enxame de fraturas',
      fractureWater: "Entrada d'água",
      caveDry: 'Caverna seca',
      caveWet: 'Caverna c/ água',
      boreHole: 'Perfuração',
      surfaceCase: 'Tubo guia',
      holeFillGravel: 'Pré-filtro',
      holeFillSeal: 'Vedação',
      wellCase: 'Revestimento',
      wellScreen: 'Filtro',
      cementPad: 'Laje de cimento',
      conflict: 'Conflito',
    },
  },
};

export const DEFAULT_COMPONENTS_CLASS_NAMES: ComponentsClassNames = {
  tooltip: {
    root: 'tooltip',
    title: 'title',
    primaryInfo: 'primaryInfo',
    secondaryInfo: 'secondaryInfo',
  },
  yAxis: 'yAxis',
  wellGroup: 'well-group',
  geologicGroup: 'geologic-group',
  lithology: {
    group: 'lithology-group',
    rect: 'lithology-rect',
  },
  fractures: {
    group: 'fractures-group',
    item: 'fracture-group',
    hitArea: 'fracture-hit',
    line: 'fracture-line',
    polyline: 'fracture-poly',
  },
  caves: {
    group: 'caves-group',
    item: 'cave-group',
    fill: 'cave-fill',
    contact: 'cave-contact',
  },
  constructionGroup: 'construction-group',
  constructionLabels: {
    group: 'construction-labels-group',
  },
  cementPad: {
    group: 'cement-pad',
    item: 'cement-pad-rect',
  },
  boreHole: {
    group: 'hole',
    rect: 'bore-hole-rect',
  },
  surfaceCase: {
    group: 'surface-case',
    rect: 'surface-case-rect',
  },
  holeFill: {
    group: 'hole-fill',
    rect: 'hole-fill-rect',
  },
  wellCase: {
    group: 'well-case',
    rect: 'well-case-rect',
  },
  wellScreen: {
    group: 'well-screen',
    rect: 'well-screen-rect',
  },
  conflict: {
    group: 'conflict',
    rect: 'conflict-rect',
  },
  unitLabels: {
    group: 'unit-labels-group',
    geoRect: 'unit-geo-rect',
    aqRect: 'unit-aq-rect',
    text: 'unit-label-text',
  },
  labels: {
    lithology: {
      group: 'lithology-labels-group',
      depth: 'lithology-depth-tip',
      label: 'lithology-label',
      divider: 'lithology-label-divider',
    },
  },
  legend: {
    border: 'wp-legend-border',
    title: 'wp-legend-title',
    item: 'wp-legend-item',
    label: 'wp-legend-label',
    fracturePoly: 'fracture-poly',
    caveFill: 'cave-fill',
    constructionRect: 'construction-rect',
  },
};

export const CSS_VAR_MAP: Record<keyof CssVarsConfig, string> = {
  lithologyStroke: '--wp-lithology-stroke',
  caveDryStroke: '--wp-cave-dry-stroke',
  caveWetStroke: '--wp-cave-wet-stroke',
  fractureDryStroke: '--wp-fracture-dry-stroke',
  fractureWetStroke: '--wp-fracture-wet-stroke',
  cementPadStroke: '--wp-cement-pad-stroke',
  boreHoleFill: '--wp-bore-hole-fill',
  boreHoleStroke: '--wp-bore-hole-stroke',
  boreHoleStrokeDasharray: '--wp-bore-hole-stroke-dasharray',
  surfaceCaseFill: '--wp-surface-case-fill',
  surfaceCaseStroke: '--wp-surface-case-stroke',
  holeFillStroke: '--wp-hole-fill-stroke',
  wellCaseFill: '--wp-well-case-fill',
  wellCaseStroke: '--wp-well-case-stroke',
  wellScreenStroke: '--wp-well-screen-stroke',
  conflictStroke: '--wp-conflict-stroke',
  lithologyStrokeWidth: '--wp-lithology-stroke-width',
  caveFillOpacity: '--wp-cave-fill-opacity',
  caveContactStrokeWidth: '--wp-cave-contact-stroke-width',
  cementPadStrokeWidth: '--wp-cement-pad-stroke-width',
  boreHoleOpacity: '--wp-bore-hole-opacity',
  boreHoleStrokeWidth: '--wp-bore-hole-stroke-width',
  surfaceCaseStrokeWidth: '--wp-surface-case-stroke-width',
  holeFillStrokeWidth: '--wp-hole-fill-stroke-width',
  wellCaseStrokeWidth: '--wp-well-case-stroke-width',
  wellScreenStrokeWidth: '--wp-well-screen-stroke-width',
  conflictStrokeWidth: '--wp-conflict-stroke-width',
  unitLabelGeologicFill: '--wp-unit-geo-fill',
  unitLabelAquiferFill: '--wp-unit-aq-fill',
  unitLabelStroke: '--wp-unit-label-stroke',
  legendBorderStrokeWidth: '--wp-legend-border-stroke-width',
  legendFractureStrokeWidth: '--wp-legend-fracture-stroke-width',
  legendFractureSideStrokeWidth: '--wp-legend-fracture-side-stroke-width',
  legendItemStrokeWidth: '--wp-legend-item-stroke-width',
};
