import { easeCubic } from 'd3';
import { RenderConfig, WellTheme } from '~/types/render.types';

export const DEFAULT_WELL_THEME: WellTheme = {
  lithology: { stroke: '#101010', strokeWidth: 1 },
  lithologyTexture: { size: 150, strokeWidth: 0.8, stroke: '#303030' },
  cave: {
    dryStroke: '#333333',
    wetStroke: '#1a6fa8',
    fillOpacity: 0.6,
    contactStrokeWidth: 1.2,
  },
  fracture: {
    dryStroke: '#000000',
    wetStroke: '#1a6fa8',
    swarm: {
      centralStrokeWidth: 1.2,
      sideStrokeWidthBase: 0.6,
      sideStrokeWidthVariance: 0.6,
    },
    single: {
      mainStrokeWidth: 1.8,
      crackStrokeWidth: 0.7,
    },
  },
  cementPad: { stroke: '#303030', strokeWidth: 2 },
  boreHole: {
    fill: '#ffffff',
    stroke: '#191919',
    strokeDasharray: '4, 3',
    opacity: 0.7,
    strokeWidth: 1.2,
  },
  surfaceCase: { stroke: '#000000', strokeWidth: 4 },
  holeFill: { stroke: '#303030', strokeWidth: 2 },
  wellCase: { fill: '#ffffff', stroke: '#303030', strokeWidth: 2 },
  wellScreen: { stroke: '#303030', strokeWidth: 2 },
  conflict: { stroke: '#e52117', strokeWidth: 4 },
  unitLabels: {
    geologicFill: '#f0f0f0',
    aquiferFill: '#dff0ff',
    stroke: '#303030',
    strokeWidth: 0.4,
    fontSize: 5.5,
    fontFamily: 'sans-serif',
    fontWeight: 400,
  },
  constructionLabels: {
    fontSize: 7.5,
    labelFill: '#ffffff',
    labelColor: '#303030',
    fontFamily: 'sans-serif',
    fontWeight: 400,
  },
  labels: {
    dividerStroke: '#888888',
    dividerStrokeWidth: 0.5,
    dividerStrokeDasharray: '2, 2',
    fontSize: 7,
    color: '#333',
    headerFont: 'monospace',
    bodyColor: '#555',
    bodyFont: 'sans-serif',
    scaleFont: 'monospace',
    depthTipFill: '#ffffff',
    depthTipRadius: 2,
    annotationBg: '#ffffff',
    annotationBgOpacity: 0.85,
    annotationRadius: 2,
    headerFontWeight: 600,
    bodyFontWeight: 400,
  },
  legend: {
    borderStrokeWidth: 0.8,
    fractureStrokeWidth: 1.5,
    fractureSideStrokeWidth: 0.8,
    itemStrokeWidth: 0.8,
    fontSize: 7,
    fontFamily: 'sans-serif',
    titleFontWeight: 'bold',
    labelFontWeight: 400,
  },
};

export const STATIC_RENDER_CONFIG: RenderConfig = {
  zoom: true,
  pan: true,
  zoomLevel: 1,
  animation: { duration: 600, ease: easeCubic },
  geologic: { xLeft: 20, xRightInset: 300 },
  layout: { pocoWidthRatio: 0.21, pocoCenterRatio: -0.39 },
  caves: {
    pathSteps: 40,
    amplitude: { ratio: 0.12, min: 1, max: 5.5 },
  },
  fractures: {
    widthMultiplier: 1.2,
    hitBuffer: { single: 8, swarm: 15 },
    swarm: {
      lineCountBase: 3,
      lineCountVariance: 11,
      spread: 18,
    },
  },
  construction: {
    cementPad: { widthMultiplier: 0.9, thicknessMultiplier: 1.3 },
    surfaceCase: { diameterPaddingRatio: 0.1 },
  },
  labels: {
    active: true,
    typeLabels: { fracture: 'fratura', cave: 'caverna' },
    depthTipHeight: 11,
    depthTipPadX: 2,
    descriptionXOffset: 20,
    descriptionMaxWidth: 250,
    stackingLineHeight: 10,
    stackingGap: 0,
    fractureLabelLeaderGap: 5,
    lithology: true,
  },
  unitLabels: {
    active: true,
    xOffset: 2,
    stripWidth: 8,
    minHeightForText: 8,
    innerDividerWidth: 1.5,
    outerEdgeWidth: 0.6,
  },
  constructionLabels: {
    active: true,
    xOffset: -12,
    labelRadius: 2,
    labelMaxWidth: 90,
    labels: {
      wellCasePrefix: 'Revest.',
      wellScreenPrefix: 'Filtro',
      wellScreenSlotPrefix: 'Ranhura:',
    },
  },
  textures: {
    pad: { background: '#ffffff', stroke: '#303030' },
    conflict: { stroke: '#E52117' },
    cave_dry: { size: 8, stroke: '#333333', background: '#ffffff' },
    cave_wet: { size: 8, stroke: '#1a6fa8', background: '#ffffff' },
    seal: { background: '#ffffff' },
    gravel_pack: { background: '#ffffff' },
    well_screen: { size: 40, strokeWidth: 2, background: '#ffffff' },
    surface_case: {
      orientation: ['vertical', 'horizontal'],
      size: 4,
      strokeWidth: 1,
      shapeRendering: 'crispEdges',
      stroke: '#303030',
      background: '#fff',
    },
  },
  legend: {
    title: 'LEGENDA',
    itemWidth: 110,
    height: 44,
    padding: 4,
    maxWidth: 700,
    borderRadius: 3,
    labels: {
      fractureSingle: 'Fratura simples',
      fractureSwarm: 'Enxame de fraturas',
      fractureWater: "Entrada d'água",
      caveDry: 'Caverna seca',
      caveWet: 'Caverna c/ água',
      boreHole: 'Perfuração',
      surfaceCase: 'Tubo guia',
      holeFillGravel: 'Pré-filtro',
      holeFillSeal: 'Vedação',
      wellCase: 'Revestimento',
      wellScreen: 'Filtro',
      cementPad: 'Laje de cimento',
      conflict: 'Conflito',
    },
  },
};

export const INTERACTIVE_RENDER_CONFIG: RenderConfig = {
  zoom: true,
  pan: true,
  zoomLevel: 1,
  animation: { duration: 600, ease: easeCubic },
  geologic: { xLeft: 6, xRightInset: 56 },
  layout: { pocoWidthRatio: 0.25, pocoCenterRatio: 0.11 },
  caves: {
    pathSteps: 40,
    amplitude: { ratio: 0.12, min: 1, max: 5.5 },
  },
  fractures: {
    widthMultiplier: 1.2,
    hitBuffer: { single: 8, swarm: 15 },
    swarm: {
      lineCountBase: 3,
      lineCountVariance: 11,
      spread: 18,
    },
  },
  construction: {
    cementPad: { widthMultiplier: 0.9, thicknessMultiplier: 1.3 },
    surfaceCase: { diameterPaddingRatio: 0.1 },
  },
  labels: {
    active: false,
    typeLabels: { fracture: 'fratura', cave: 'caverna' },
    depthTipHeight: 11,
    depthTipPadX: 2,
    descriptionXOffset: 78,
    descriptionMaxWidth: 226,
    stackingLineHeight: 11,
    stackingGap: 0,
  },
  unitLabels: {
    active: false,
    xOffset: 0,
    stripWidth: 8,
    minHeightForText: 8,
    innerDividerWidth: 1.5,
    outerEdgeWidth: 0.6,
  },
  constructionLabels: {
    active: false,
    xOffset: 10,
    labelRadius: 2,
    labels: {
      wellCasePrefix: 'Revest.',
      wellScreenPrefix: 'Filtro',
      wellScreenSlotPrefix: 'Ranhura:',
    },
  },
  textures: {
    pad: { background: '#ffffff', stroke: '#303030' },
    conflict: { stroke: '#E52117' },
    cave_dry: { size: 8, stroke: '#333333', background: '#ffffff' },
    cave_wet: { size: 8, stroke: '#1a6fa8', background: '#ffffff' },
    seal: { background: '#ffffff' },
    gravel_pack: { background: '#ffffff' },
    well_screen: { size: 40, strokeWidth: 2, background: '#ffffff' },
    surface_case: {
      orientation: ['vertical', 'horizontal'],
      size: 4,
      strokeWidth: 1,
      shapeRendering: 'crispEdges',
      stroke: '#303030',
      background: '#fff',
    },
  },
  legend: {
    title: 'LEGENDA',
    itemWidth: 110,
    height: 44,
    padding: 4,
    maxWidth: 700,
    borderRadius: 3,
    labels: {
      fractureSingle: 'Fratura simples',
      fractureSwarm: 'Enxame de fraturas',
      fractureWater: "Entrada d'água",
      caveDry: 'Caverna seca',
      caveWet: 'Caverna c/ água',
      boreHole: 'Perfuração',
      surfaceCase: 'Tubo guia',
      holeFillGravel: 'Pré-filtro',
      holeFillSeal: 'Vedação',
      wellCase: 'Revestimento',
      wellScreen: 'Filtro',
      cementPad: 'Laje de cimento',
      conflict: 'Conflito',
    },
  },
};
