import { Texture } from '../types/textures';

export const FGDC_TEXTURES_OPTIONS: Texture[] = [
  // --- Surficial Patterns (Series 100) ---
  { code: 101, label: 'Unconsolidated material' },
  { code: 102, label: 'Alluvium' },
  { code: 103, label: 'Terrace deposit' },
  { code: 104, label: 'Floodplain deposit' },
  { code: 105, label: 'Fan or pediment deposit' },
  { code: 106, label: 'Eolian sand' },
  { code: 107, label: 'Silt or loess' },
  { code: 108, label: 'Clay deposit' },
  { code: 109, label: 'Colluvium' },
  { code: 110, label: 'Gravel deposit' },
  { code: 111, label: 'Residual deposit' },
  { code: 112, label: 'Playa deposit' },
  { code: 113, label: 'Lacustrine deposit' },
  { code: 114, label: 'Marine deposit' },
  { code: 115, label: 'Beach or bar deposit' },
  { code: 116, label: 'Organic deposit or peat' },
  { code: 117, label: 'Swamp or marsh deposit' },
  { code: 118, label: 'Soil' },
  { code: 119, label: 'Fill or artificial deposit' },
  { code: 120, label: 'Surficial pattern 120' },
  { code: 121, label: 'Surficial pattern 121' },
  { code: 122, label: 'Surficial pattern 122' },
  { code: 123, label: 'Surficial pattern 123' },
  { code: 124, label: 'Surficial pattern 124' },
  { code: 125, label: 'Surficial pattern 125' },
  { code: 126, label: 'Surficial pattern 126' },
  { code: 127, label: 'Surficial pattern 127' },
  { code: 128, label: 'Surficial pattern 128' },
  { code: 129, label: 'Surficial pattern 129' },
  { code: 130, label: 'Surficial pattern 130' },
  { code: 131, label: 'Surficial pattern 131' },
  { code: 132, label: 'Surficial pattern 132' },
  { code: 133, label: 'Surficial pattern 133' },
  { code: 134, label: 'Surficial pattern 134' },
  { code: 135, label: 'Surficial pattern 135' },
  { code: 136, label: 'Surficial pattern 136' },
  { code: 137, label: 'Surficial pattern 137' },
  // --- Sedimentary Patterns (Series 200) ---
  { code: 201, label: 'Sedimentary pattern 201' },
  { code: 202, label: 'Sedimentary pattern 202' },
  { code: 203, label: 'Sedimentary pattern 203' },
  { code: 204, label: 'Sedimentary pattern 204' },
  { code: 205, label: 'Sedimentary pattern 205' },
  { code: 206, label: 'Sedimentary pattern 206' },
  { code: 207, label: 'Sedimentary pattern 207' },
  { code: 208, label: 'Sedimentary pattern 208' },
  { code: 209, label: 'Sedimentary pattern 209' },
  { code: 210, label: 'Sedimentary pattern 210' },
  { code: 211, label: 'Sedimentary pattern 211' },
  { code: 212, label: 'Sedimentary pattern 212' },
  { code: 213, label: 'Sedimentary pattern 213' },
  { code: 214, label: 'Sedimentary pattern 214' },
  { code: 215, label: 'Sedimentary pattern 215' },
  { code: 216, label: 'Sedimentary pattern 216' },
  { code: 217, label: 'Sedimentary pattern 217' },
  { code: 218, label: 'Sedimentary pattern 218' },
  { code: 219, label: 'Sedimentary pattern 219' },
  { code: 220, label: 'Sedimentary pattern 220' },
  { code: 221, label: 'Sedimentary pattern 221' },
  { code: 222, label: 'Sedimentary pattern 222' },
  { code: 223, label: 'Sedimentary pattern 223' },
  { code: 224, label: 'Sedimentary pattern 224' },
  { code: 225, label: 'Sedimentary pattern 225' },
  { code: 226, label: 'Sedimentary pattern 226' },
  { code: 227, label: 'Sedimentary pattern 227' },
  { code: 228, label: 'Sedimentary pattern 228' },
  { code: 229, label: 'Sedimentary pattern 229' },
  { code: 230, label: 'Sedimentary pattern 230' },
  { code: 231, label: 'Sedimentary pattern 231' },
  { code: 232, label: 'Sedimentary pattern 232' },
  { code: 233, label: 'Sedimentary pattern 233' },
  // --- Igneous Patterns (Series 300) ---
  { code: 301, label: 'Igneous pattern 301' },
  { code: 302, label: 'Igneous pattern 302' },
  { code: 303, label: 'Igneous pattern 303' },
  { code: 304, label: 'Igneous pattern 304' },
  { code: 305, label: 'Igneous pattern 305' },
  { code: 306, label: 'Igneous pattern 306' },
  { code: 307, label: 'Igneous pattern 307' },
  { code: 308, label: 'Igneous pattern 308' },
  { code: 309, label: 'Igneous pattern 309' },
  { code: 310, label: 'Igneous pattern 310' },
  { code: 311, label: 'Igneous pattern 311' },
  { code: 312, label: 'Igneous pattern 312' },
  { code: 313, label: 'Igneous pattern 313' },
  { code: 314, label: 'Igneous pattern 314' },
  { code: 315, label: 'Igneous pattern 315' },
  { code: 316, label: 'Igneous pattern 316' },
  { code: 317, label: 'Igneous pattern 317' },
  { code: 318, label: 'Igneous pattern 318' },
  { code: 319, label: 'Igneous pattern 319' },
  { code: 320, label: 'Igneous pattern 320' },
  { code: 321, label: 'Igneous pattern 321' },
  { code: 322, label: 'Igneous pattern 322' },
  { code: 323, label: 'Igneous pattern 323' },
  { code: 324, label: 'Igneous pattern 324' },
  { code: 325, label: 'Igneous pattern 325' },
  { code: 326, label: 'Igneous pattern 326' },
  { code: 327, label: 'Igneous pattern 327' },
  { code: 328, label: 'Igneous pattern 328' },
  { code: 329, label: 'Igneous pattern 329' },
  { code: 330, label: 'Igneous pattern 330' },
  { code: 331, label: 'Igneous pattern 331' },
  // --- Miscellaneous and Metamorphic Patterns (Series 400) ---
  { code: 401, label: 'Miscellaneous pattern 401' },
  { code: 402, label: 'Miscellaneous pattern 402' },
  { code: 403, label: 'Miscellaneous pattern 403' },
  { code: 404, label: 'Miscellaneous pattern 404' },
  { code: 405, label: 'Miscellaneous pattern 405' },
  { code: 406, label: 'Miscellaneous pattern 406' },
  { code: 407, label: 'Miscellaneous pattern 407' },
  { code: 408, label: 'Miscellaneous pattern 408' },
  { code: 409, label: 'Miscellaneous pattern 409' },
  { code: 410, label: 'Miscellaneous pattern 410' },
  { code: 411, label: 'Miscellaneous pattern 411' },
  { code: 412, label: 'Miscellaneous pattern 412' },
  { code: 413, label: 'Miscellaneous pattern 413' },
  { code: 414, label: 'Miscellaneous pattern 414' },
  { code: 415, label: 'Miscellaneous pattern 415' },
  { code: 416, label: 'Miscellaneous pattern 416' },
  { code: 417, label: 'Miscellaneous pattern 417' },
  { code: 418, label: 'Miscellaneous pattern 418' },
  { code: 419, label: 'Miscellaneous pattern 419' },
  { code: 420, label: 'Miscellaneous pattern 420' },
  { code: 421, label: 'Miscellaneous pattern 421' },
  { code: 422, label: 'Miscellaneous pattern 422' },
  { code: 423, label: 'Miscellaneous pattern 423' },
  { code: 424, label: 'Miscellaneous pattern 424' },
  { code: 425, label: 'Miscellaneous pattern 425' },
  { code: 426, label: 'Miscellaneous pattern 426' },
  { code: 427, label: 'Miscellaneous pattern 427' },
  { code: 428, label: 'Miscellaneous pattern 428' },
  { code: 429, label: 'Miscellaneous pattern 429' },
  { code: 430, label: 'Miscellaneous pattern 430' },
  { code: 431, label: 'Miscellaneous pattern 431' },
  { code: 432, label: 'Miscellaneous pattern 432' },
  { code: 433, label: 'Miscellaneous pattern 433' },
  { code: 434, label: 'Miscellaneous pattern 434' },
  { code: 435, label: 'Miscellaneous pattern 435' },
  { code: 436, label: 'Miscellaneous pattern 436' },
  // --- Glacial Patterns (Series 500) ---
  { code: 521, label: 'Glacial pattern 521' },
  { code: 522, label: 'Glacial pattern 522' },
  { code: 523, label: 'Glacial pattern 523' },
  { code: 524, label: 'Glacial pattern 524' },
  { code: 530, label: 'Glacial pattern 530' },
  { code: 531, label: 'Glacial pattern 531' },
  { code: 532, label: 'Glacial pattern 532' },
  { code: 533, label: 'Glacial pattern 533' },
  { code: 534, label: 'Glacial pattern 534' },
  { code: 535, label: 'Glacial pattern 535' },
  { code: 536, label: 'Glacial pattern 536' },
  { code: 537, label: 'Glacial pattern 537' },
  { code: 538, label: 'Glacial pattern 538' },
  { code: 580, label: 'Glacial pattern 580' },
  { code: 581, label: 'Glacial pattern 581' },
  { code: 582, label: 'Glacial pattern 582' },
  { code: 583, label: 'Glacial pattern 583' },
  { code: 584, label: 'Glacial pattern 584' },
  { code: 585, label: 'Glacial pattern 585' },
  { code: 586, label: 'Glacial pattern 586' },
  { code: 587, label: 'Glacial pattern 587' },
  { code: 588, label: 'Glacial pattern 588' },
  { code: 589, label: 'Glacial pattern 589' },
  { code: 591, label: 'Periglacial pattern 591' },
  { code: 592, label: 'Periglacial pattern 592' },
  { code: 593, label: 'Periglacial pattern 593' },
  { code: 594, label: 'Periglacial pattern 594' },
  { code: 595, label: 'Periglacial pattern 595' },
  // --- Sedimentary Lithology Patterns (Series 600) ---
  { code: 601, label: 'Gravel or conglomerate (1st option)' },
  { code: 602, label: 'Gravel or conglomerate (2nd option)' },
  { code: 603, label: 'Crossbedded gravel or conglomerate' },
  { code: 605, label: 'Breccia (1st option)' },
  { code: 606, label: 'Breccia (2nd option)' },
  { code: 607, label: 'Massive sand or sandstone' },
  { code: 608, label: 'Bedded sand or sandstone' },
  { code: 609, label: 'Crossbedded sand or sandstone (1st option)' },
  { code: 610, label: 'Crossbedded sand or sandstone (2nd option)' },
  { code: 611, label: 'Ripple-bedded sand or sandstone' },
  { code: 612, label: 'Argillaceous or shaly sandstone' },
  { code: 613, label: 'Calcareous sandstone' },
  { code: 614, label: 'Dolomitic sandstone' },
  { code: 616, label: 'Silt, siltstone, or shaly silt' },
  { code: 617, label: 'Calcareous siltstone' },
  { code: 618, label: 'Dolomitic siltstone' },
  { code: 619, label: 'Sandy or silty shale' },
  { code: 620, label: 'Clay or clay shale' },
  { code: 621, label: 'Cherty shale' },
  { code: 622, label: 'Dolomitic shale' },
  { code: 623, label: 'Calcareous shale or marl' },
  { code: 624, label: 'Carbonaceous shale' },
  { code: 625, label: 'Oil shale' },
  { code: 626, label: 'Chalk' },
  { code: 627, label: 'Limestone' },
  { code: 628, label: 'Clastic limestone' },
  { code: 629, label: 'Fossiliferous clastic limestone' },
  { code: 630, label: 'Nodular or irregularly bedded limestone' },
  {
    code: 631,
    label: 'Limestone, irregular (burrow?) fillings of saccharoidal dolomite',
  },
  { code: 632, label: 'Crossbedded limestone' },
  { code: 633, label: 'Cherty crossbedded limestone' },
  { code: 634, label: 'Cherty and sandy crossbedded clastic limestone' },
  { code: 635, label: 'Oolitic limestone' },
  { code: 636, label: 'Sandy limestone' },
  { code: 637, label: 'Silty limestone' },
  { code: 638, label: 'Argillaceous or shaly limestone' },
  { code: 639, label: 'Cherty limestone (1st option)' },
  { code: 640, label: 'Cherty limestone (2nd option)' },
  { code: 641, label: 'Dolomitic limestone, limy dolostone, or limy dolomite' },
  { code: 642, label: 'Dolostone or dolomite' },
  { code: 643, label: 'Crossbedded dolostone or dolomite' },
  { code: 644, label: 'Oolitic dolostone or dolomite' },
  { code: 645, label: 'Sandy dolostone or dolomite' },
  { code: 646, label: 'Silty dolostone or dolomite' },
  { code: 647, label: 'Argillaceous or shaly dolostone or dolomite' },
  { code: 648, label: 'Cherty dolostone or dolomite' },
  { code: 649, label: 'Bedded chert (1st option)' },
  { code: 650, label: 'Bedded chert (2nd option)' },
  { code: 651, label: 'Fossiliferous bedded chert' },
  { code: 652, label: 'Fossiliferous rock' },
  { code: 653, label: 'Diatomaceous rock' },
  { code: 654, label: 'Subgraywacke' },
  { code: 655, label: 'Crossbedded subgraywacke' },
  { code: 656, label: 'Ripple-bedded subgraywacke' },
  { code: 657, label: 'Peat' },
  { code: 658, label: 'Coal' },
  { code: 659, label: 'Bony coal or impure coal' },
  { code: 660, label: 'Underclay' },
  { code: 661, label: 'Flint clay' },
  { code: 662, label: 'Bentonite' },
  { code: 663, label: 'Glauconite' },
  { code: 664, label: 'Limonite' },
  { code: 665, label: 'Siderite' },
  { code: 666, label: 'Phosphatic-nodular rock' },
  { code: 667, label: 'Gypsum' },
  { code: 668, label: 'Salt' },
  { code: 669, label: 'Interbedded sandstone and siltstone' },
  { code: 670, label: 'Interbedded sandstone and shale' },
  { code: 671, label: 'Interbedded ripple-bedded sandstone and shale' },
  {
    code: 672,
    label: 'Interbedded shale and silty limestone (shale dominant)',
  },
  {
    code: 673,
    label: 'Interbedded shale and limestone, shale dominant (1st option)',
  },
  {
    code: 674,
    label: 'Interbedded shale and limestone, shale dominant (2nd option)',
  },
  {
    code: 675,
    label: 'Interbedded calcareous shale and limestone (shale dominant)',
  },
  { code: 676, label: 'Interbedded silty limestone and shale' },
  { code: 677, label: 'Interbedded limestone and shale (1st option)' },
  { code: 678, label: 'Interbedded limestone and shale (2nd option)' },
  { code: 679, label: 'Interbedded limestone and shale (limestone dominant)' },
  { code: 680, label: 'Interbedded limestone and calcareous shale' },
  { code: 681, label: 'Till or diamicton (1st option)' },
  { code: 682, label: 'Till or diamicton (2nd option)' },
  { code: 683, label: 'Till or diamicton (3rd option)' },
  { code: 684, label: 'Loess (1st option)' },
  { code: 685, label: 'Loess (2nd option)' },
  { code: 686, label: 'Loess (3rd option)' },
  // --- Metamorphic Lithology Patterns (Series 700) ---
  { code: 701, label: 'Metamorphism' },
  { code: 702, label: 'Quartzite' },
  { code: 703, label: 'Slate' },
  { code: 704, label: 'Schistose or gneissoid granite' },
  { code: 705, label: 'Schist' },
  { code: 706, label: 'Contorted schist' },
  { code: 707, label: 'Schist and gneiss' },
  { code: 708, label: 'Gneiss' },
  { code: 709, label: 'Contorted gneiss' },
  { code: 710, label: 'Soapstone, talc, or serpentinite' },
  // --- Igneous and Vein-Matter Lithology Patterns (Series 700 continued) ---
  { code: 711, label: 'Tuffaceous rock' },
  { code: 712, label: 'Crystal tuff' },
  { code: 713, label: 'Devitrified tuff' },
  { code: 714, label: 'Volcanic breccia and tuff' },
  { code: 715, label: 'Volcanic breccia or agglomerate' },
  { code: 716, label: 'Zeolitic rock' },
  { code: 717, label: 'Basaltic flows' },
  { code: 718, label: 'Granite (1st option)' },
  { code: 719, label: 'Granite (2nd option)' },
  { code: 720, label: 'Banded igneous rock' },
  { code: 721, label: 'Igneous rock (1st option)' },
  { code: 722, label: 'Igneous rock (2nd option)' },
  { code: 723, label: 'Igneous rock (3rd option)' },
  { code: 724, label: 'Igneous rock (4th option)' },
  { code: 725, label: 'Igneous rock (5th option)' },
  { code: 726, label: 'Igneous rock (6th option)' },
  { code: 727, label: 'Igneous rock (7th option)' },
  { code: 728, label: 'Igneous rock (8th option)' },
  { code: 729, label: 'Porphyritic rock (1st option)' },
  { code: 730, label: 'Porphyritic rock (2nd option)' },
  { code: 731, label: 'Vitrophyre' },
  { code: 732, label: 'Quartz' },
  { code: 733, label: 'Ore' },
];
