import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import { IconButton, Button, Link as LinkMaterial } from '@mui/material';

import Behance from '../public/assets/behance_1.svg';
import Linkedin from '../public/assets/linkedin_1.svg';
import Email from '../public/assets/email_1.svg';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.root}>
      <div id="about" className={`${styles.tile} ${styles.hero}`}>
        <div className={`${styles.tileContent} ${styles.heroContent}`}>
          <div className={`${styles.lWrapper}`}>
            <h3 className={styles.tileTitle}>
              Crie perfis geológicos e construtivos de poços e sondagens com
              facilidade
            </h3>
            <Link href="/editor" passHref>

            <Button
              variant="outlined"
              className={styles.btn}
              onClick={() => {
                // @ts-ignore
                if (window.gtag) {
                  // @ts-ignore
                  window.gtag(
                    'event',
                    'button clicked',
                    'User Interaction',
                    'editor'
                  );
                }
              }}
            >
              Edite seu perfil
            </Button>
            </Link>
          </div>
          <div className={`${styles.rWrapper}`} />
        </div>
      </div>
      <div id="about" className={`${styles.tile} ${styles.info}`}>
        <div className={`${styles.tileContent} ${styles.infoContent}`}>
          <div className={`${styles.lWrapper}`} />
          <div className={`${styles.rWrapper}`}>
            <h3 className={styles.tileTitle}>
              Um programa destinado para geólogos, hidrogeólogos e demais
              profissionais
            </h3>
            <p className={styles.tileText}>
              O <strong>Well Profiler</strong> é uma ferramenta que torna fácil
              a confecção e visualização de perfis geológico-construtivos de
              poços. A ferramenta é gratuita para uso e conta com conjunto
              crescente recursos úteis que deverão ser adicionados com o tempo.
            </p>
          </div>
        </div>
      </div>
      <footer className={`${styles.tile} ${styles.about}`}>
        <div className={`${styles.tileContent}`}>
          <p className={styles.tileText}>
            Criado e desenvolvido por Rafael Gomes
          </p>
          <div className={styles.socialBtnsContainer}>
            <LinkMaterial
              className={styles.socialBtn}
              component={IconButton}
              onClick={() => {
                // @ts-ignore
                if (window.gtag) {
                  // @ts-ignore
                  window.gtag(
                    'event',
                    'button clicked',
                    'Link to social media',
                    'behance'
                  );
                }
              }}
              href="https://www.behance.net/rafaeelneto"
              target="_blank"
            >
              <Behance />
            </LinkMaterial>
            <LinkMaterial
              className={styles.socialBtn}
              component={IconButton}
              onClick={() => {
                // @ts-ignore
                if (window.gtag) {
                  // @ts-ignore
                  window.gtag(
                    'event',
                    'button clicked',
                    'Link to social media',
                    'linkedinho'
                  );
                }
              }}
              href="https://www.linkedin.com/in/rafaeelneto/"
              target="_blank"
            >
              <Linkedin />
            </LinkMaterial>

            <LinkMaterial
              className={styles.socialBtn}
              component={IconButton}
              onClick={() => {
                // @ts-ignore
                if (window.gtag) {
                  // @ts-ignore
                  window.gtag(
                    'event',
                    'button clicked',
                    'Link to social media',
                    'email'
                  );
                }
              }}
              href="mailto: rafaelneto.g@gmail.com"
              target="_blank"
            >
              <Email />
            </LinkMaterial>
          </div>
        </div>
      </footer>
    </div>
    </div>
  )
}

export default Home
